name: build

on:
  push:
    branches:
      - main
  pull_request:

env:
  FORCE_COLOR: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./.github/actions/pnpm-install
      - run: pnpm check
      - run: pnpm build
      - run: pnpm test
